### ISSUE TITLE
Yinote window doesnt close in Chrome

### ISSUE THREAD

**Issue by gandalf34** [shuowu/yi-note#106]
**Describe the bug**

The yinote window open on the right hand side close in firefox but doesnt close in Chrome.

**To Reproduce**
1. Click on extension . Yinote will open
3. Click on the arrow > at he right hand side of the Search field. 
4. Nothing happens.

**Expected behavior**
It is expected to close by sliding to the right 

**Screenshots**

**Browser (please complete the following information):**
 -Version 96.0.4664.45 (Official Build) (64-bit)
 -

**Additional context**
Add any other context about the problem here

https://user-images.githubusercontent.com/86377241/143216583-cb9f1214-0580-4f7d-af34-53f552c9e92d.mp4

.

**Comment by hawkiboy** [comment]
Agree, this makes for a BAD experience.

**Comment by quentin-mckay** [comment]
Same issue for me. I'm on Chrome Version 99.0.4844.74 (Official Build) (64-bit)

**Comment by rcsoul** [comment]
The same thing happens to me.

**Comment by chris2052** [comment]
Same in Brave-Browser

**Comment by phanirithvij** [comment]
same of #105

**Comment by No2515** [comment]
No fix yet?

**Comment by nikevelik** [comment]
I have the same issue

**Comment by lemattma** [comment]
@shuowu I've been debugging this issue and it seems to be related to the file `packages/extension/src/ui/containers/App/styled.js` on the `transform` property:

```css
export const StyledDrawer = styled.div`
  ...

  transition: transform 0.3s;
  /* it's not updating the value, but props.open does change. Maybe some cache issue? */
  transform: ${props => (props.open ? 'translateX(0)' : 'translateX(100%)')}; 

  ...
`;
```

I'll keep digging but if you know how to fix it please let me know.
